apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-upgrade
  namespace: {{ include "codefresh-runner.namespace" . }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "codefresh-runner.serviceAccountName" . }}
      containers:
      - name: codefresh
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/script/upgrade.sh"]
        env:
          {{- if .Values.env.proxy }}
          {{- range $key, $value := .Values.env.proxy }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          - name: CODEFRESH_TOKEN
          {{- if .Values.env.codefreshTokenSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ required "Require a secret name that contains the codefresh token" .Values.env.codefreshTokenSecret.name }}
                key: {{ required "Require a secret key that contains the codefresh token" .Values.env.codefreshTokenSecret.key }}
          {{- else }}
            value: {{ .Values.env.codefreshToken }}
          {{- end }}
          - name: CF_ARG_KUBE_NAMESPACE
            value: {{ include "codefresh-runner.namespace" . }}
          - name: CF_ARG_KUBE_CONTEXT_NAME
            value: inClusterContext
          - name: CF_AGENT_NAME
            value: {{ .Values.env.codefreshAgentName }}
          - name: CF_URL
            value: {{ .Values.env.codefreshURL }}
          - name: CF_ARG_docker-registry
            value: {{ .Values.env.dockerRegistry }}
        volumeMounts:
        - name: upgrade-script
          mountPath: /script/upgrade.sh
          subPath: upgrade.sh
      volumes:
        - name: upgrade-script
          configMap:
            name: {{ .Release.Name }}-upgrade-script
            defaultMode: 0777   
      restartPolicy: Never
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range $sec := .Values.image.imagePullSecrets }}
        - name: {{$sec | quote }}
      {{- end }}
      {{- end }}
  backoffLimit: 4